import { Heart, Sparkles, Star, Award, Crown, Gift } from "lucide-react";

export const ALL_MILESTONES = [
  {
    days: 7,
    label: "1 Tuần",
    desc: "Bắt đầu hành trình yêu thương",
    icon: Heart,
    colors: "bg-pink-100 text-pink-500",
    iconColor: "fill-pink-400",
  },
  {
    days: 30,
    label: "1 Tháng",
    desc: "Tháng đầu tiên bên nhau",
    icon: Sparkles,
    colors: "bg-love-100 text-love-500",
    iconColor: "fill-love-400 text-love-400",
  },
  {
    days: 50,
    label: "50 Ngày",
    desc: "50 ngày đầy ắp tiếng cười",
    icon: Star,
    colors: "bg-amber-100 text-amber-500",
    iconColor: "fill-amber-400 text-amber-400",
  },
  {
    days: 100,
    label: "100 Ngày",
    desc: "Một cột mốc đáng nhớ",
    icon: Heart,
    colors: "bg-purple-100 text-purple-500",
    iconColor: "fill-purple-500 text-purple-500",
  },
  {
    days: 200,
    label: "200 Ngày",
    desc: "Cùng nhau vượt qua nhiều điều",
    icon: Award,
    colors: "bg-emerald-100 text-emerald-500",
    iconColor: "text-emerald-500",
  },
  {
    days: 365,
    label: "1 Năm",
    desc: "Chúc mừng kỷ niệm 1 năm!",
    icon: Crown,
    colors: "bg-rose-100 text-rose-500",
    iconColor: "fill-rose-500 text-rose-500",
  },
  {
    days: 500,
    label: "500 Ngày",
    desc: "Nửa ngàn ngày yêu",
    icon: Heart,
    colors: "bg-pink-100 text-pink-500",
    iconColor: "fill-pink-500 text-pink-500",
  },
  {
    days: 730,
    label: "2 Năm",
    desc: "Kỷ niệm 2 năm gắn bó",
    icon: Crown,
    colors: "bg-rose-100 text-rose-500",
    iconColor: "fill-rose-500 text-rose-500",
  },
  {
    days: 1000,
    label: "1000 Ngày",
    desc: "Ngàn ngày yêu không đổi thay",
    icon: Crown,
    colors: "bg-yellow-100 text-yellow-600",
    iconColor: "fill-yellow-500 text-yellow-500",
  },
  {
    days: 1095,
    label: "3 Năm",
    desc: "Kỷ niệm 3 năm đậm sâu",
    icon: Sparkles,
    colors: "bg-indigo-100 text-indigo-500",
    iconColor: "fill-indigo-500 text-indigo-500",
  },
  {
    days: 1460,
    label: "4 Năm",
    desc: "Kỷ niệm 4 năm chung đôi",
    icon: Heart,
    colors: "bg-rose-100 text-rose-500",
    iconColor: "fill-rose-500 text-rose-500",
  },
  {
    days: 1825,
    label: "5 Năm",
    desc: "Kỷ niệm nửa thập kỷ yêu nhau",
    icon: Award,
    colors: "bg-purple-100 text-purple-600",
    iconColor: "fill-purple-500 text-purple-600",
  },
  {
    days: 2000,
    label: "2000 Ngày",
    desc: "Chặng đường gắn bó",
    icon: Award,
    colors: "bg-emerald-100 text-emerald-500",
    iconColor: "text-emerald-500",
  },
  {
    days: 2190,
    label: "6 Năm",
    desc: "Kỷ niệm 6 năm trọn vẹn",
    icon: Star,
    colors: "bg-blue-100 text-blue-500",
    iconColor: "fill-blue-400 text-blue-500",
  },
  {
    days: 2555,
    label: "7 Năm",
    desc: "Kỷ niệm 7 năm đồng hành",
    icon: Heart,
    colors: "bg-pink-100 text-pink-500",
    iconColor: "fill-pink-400 text-pink-500",
  },
  {
    days: 2920,
    label: "8 Năm",
    desc: "Kỷ niệm 8 năm êm đềm",
    icon: Sparkles,
    colors: "bg-amber-100 text-amber-500",
    iconColor: "fill-amber-400 text-amber-500",
  },
  {
    days: 3000,
    label: "3000 Ngày",
    desc: "Đồng hành qua mọi thăng trầm",
    icon: Heart,
    colors: "bg-rose-100 text-rose-500",
    iconColor: "fill-rose-500 text-rose-500",
  },
  {
    days: 3285,
    label: "9 Năm",
    desc: "Kỷ niệm 9 năm đong đầy",
    icon: Gift,
    colors: "bg-teal-100 text-teal-600",
    iconColor: "fill-teal-500 text-teal-600",
  },
  {
    days: 3650,
    label: "10 Năm",
    desc: "Kỷ niệm 1 thập kỷ yêu nhau",
    icon: Crown,
    colors: "bg-yellow-100 text-yellow-600",
    iconColor: "fill-yellow-500 text-yellow-500",
  },
  {
    days: 4000,
    label: "4000 Ngày",
    desc: "Trao nhau sự thấu hiểu",
    icon: Sparkles,
    colors: "bg-blue-100 text-blue-500",
    iconColor: "fill-blue-400 text-blue-400",
  },
  {
    days: 5000,
    label: "5000 Ngày",
    desc: "Tình yêu mặn nồng bền chặt",
    icon: Star,
    colors: "bg-amber-100 text-amber-500",
    iconColor: "fill-amber-400 text-amber-400",
  },
  {
    days: 6000,
    label: "6000 Ngày",
    desc: "Trái tim luôn hướng về nhau",
    icon: Heart,
    colors: "bg-pink-100 text-pink-500",
    iconColor: "fill-pink-500 text-pink-500",
  },
  {
    days: 7000,
    label: "7000 Ngày",
    desc: "Mãi mãi không rời xa",
    icon: Gift,
    colors: "bg-purple-100 text-purple-500",
    iconColor: "text-purple-500",
  },
  {
    days: 8000,
    label: "8000 Ngày",
    desc: "Tình yêu tuyệt vời nhất",
    icon: Award,
    colors: "bg-emerald-100 text-emerald-500",
    iconColor: "text-emerald-500",
  },
  {
    days: 9000,
    label: "9000 Ngày",
    desc: "Hạnh phúc luôn đong đầy",
    icon: Heart,
    colors: "bg-rose-100 text-rose-500",
    iconColor: "fill-rose-500 text-rose-500",
  },
  {
    days: 10000,
    label: "10000 Ngày",
    desc: "Một tình yêu trọn đời",
    icon: Crown,
    colors: "bg-yellow-100 text-yellow-600",
    iconColor: "fill-yellow-500 text-yellow-500",
  },
] as const;